site_name: Connect and File Transfer course
repo_url: https://github.com/UPPMAX/naiss_file_transfer_course
edit_uri: blob/main/docs/

nav:
  - Start: index.md
  - Learning outcomes: learning_outcomes.md
  - Prerequisites: prereqs/README.md
  - Course dates: course_dates.md
  - Schedule: schedule.md
  - Connect:
    - sessions/intro_connect/README.md
    - Login with terminal: sessions/login_terminal/README.md
    - Login to remote desktop: sessions/login_remote_desktop/README.md
  - File transfer:
    - sessions/intro_file_transfer.md
    - File transfer using scp: sessions/scp/README.md
    - File transfer using FileZilla: sessions/filezilla/README.md
    - File transfer using rsync: sessions/rsync/README.md
    - File transfer using sftp: sessions/sftp/README.md
    - File transfer between clusters: sessions/cluster2cluster/README.md
    - Summary: sessions/summary.md
  - Misc:
    - Acknowledgements: acknowledgements.md
    - Code of conduct: CODE_OF_CONDUCT.md
    - Communication: communication/README.md
    - Contributing: CONTRIBUTING.md
    - Curriculum: curriculum.md
    - Data: data/README.md
    - Deploy website locally: deploy_locally.md
    - Evaluation: evaluation.md
    - Evaluations: evaluations/README.md
    - Frequently asked questions: faq/README.md
    - Lesson plans: lesson_plans/README.md
    - Meeting notes: meeting_notes/README.md
    - Reflections: reflections/README.md
  - Contact us: contact_us.md

theme:
  name: material
  greetings: Welcome to the NAISS Connect and File Transfer course
  font:
    text: Lato
    code: JetBrains Mono
  logo: logo/naiss_logo_white.png
  palette:
    primary: indigo

  # Keyboard shortcuts for navigation, from https://www.mkdocs.org/user-guide/choosing-your-theme/
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    
# For NAISS color gradient at top
extra_css:
  - stylesheets/extra.css


not_in_nav: |
  invitation_short.md
  scratch_intermediate_linux.md
  communication/invitations.md
  communication/registration_form.md
  communication/welcome_email.md
  communication/welcome_email_may2025.md
  communication/welcome_email_sep2025.md
  data/counts/20250307/README.md
  evaluations/20250307/README.md
  evaluations/20250516/README.md
  evaluations/20250905/README.md
  evaluations/20251114/README.md
  evaluations/20260202/README.md
  evaluations/20260512/README.md
  lesson_plans/20250307/README.md
  lesson_plans/20250516/README.md
  lesson_plans/20250905/README.md
  lesson_plans/20251114/README.md
  lesson_plans/20260202/README.md
  lesson_plans/20260512/README.md
  meeting_notes/20241121.md
  meeting_notes/20250310.md
  meeting_notes/20250515.md
  meeting_notes/20250905.md
  planning/notes.md
  planning/old_README.md
  reflections/20250307/README.md
  reflections/20250516/README.md
  reflections/20250905/README.md
  reflections/20251114/README.md
  reflections/20260202/README.md
  reflections/20260512/README.md
  sessions/choose_next.md
  sessions/transfer_tips/README.md

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
