[project]
site_name = "File transfer course"
site_url = "https://uppmax.github.io/naiss_file_transfer_course/"
repo_url = "https://github.com/UPPMAX/naiss_file_transfer_course"

nav = [
  { "Start" = "index.md"},
  "learning_outcomes.md",
  "prereqs/README.md",
  "course_dates.md",
  "schedule.md",
  "contact_us.md"
]
